# Generated by Django 3.2.3 on 2021-05-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wzrost', models.IntegerField(max_length=3)),
                ('popreg', models.IntegerField(max_length=3)),
                ('nadpecie', models.IntegerField(max_length=3)),
                ('added_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('wzrost', 'popreg', 'nadpecie'),
            },
        ),
        migrations.CreateModel(
            name='RasaKoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Kon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=250)),
                ('birthday_date', models.DateField()),
                ('added_time', models.DateTimeField(auto_now_add=True)),
                ('rasa_koni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konie', to='konie.rasakoni')),
            ],
            options={
                'ordering': ('imie',),
            },
        ),
    ]
