# Generated by Django 3.2.3 on 2021-05-26 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametry',
            options={'ordering': ('kon', 'wzrost', 'popreg', 'nadpecie')},
        ),
        migrations.AddField(
            model_name='parametry',
            name='kon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='konie', to='konie.kon'),
            preserve_default=False,
        ),
    ]
