# Generated by Django 3.2.3 on 2021-06-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0002_auto_20210526_1235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonitacja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ', models.IntegerField(max_length=2)),
                ('glowa', models.IntegerField(max_length=1)),
                ('noga_przod', models.IntegerField(max_length=1)),
                ('noga_tyl', models.IntegerField(max_length=1)),
                ('kopyta', models.IntegerField(max_length=1)),
                ('step', models.IntegerField(max_length=2)),
                ('klus', models.IntegerField(max_length=2)),
                ('ogolny', models.IntegerField(max_length=2)),
                ('razem', models.IntegerField(max_length=2)),
                ('kon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonitacja_konie', to='konie.kon')),
            ],
            options={
                'ordering': ('kon', 'typ', 'glowa', 'noga_przod', 'noga_tyl', 'kopyta', 'step', 'klus', 'ogolny', 'razem'),
            },
        ),
    ]
