# Generated by Django 3.2.3 on 2021-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0003_bonitacja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonitacja',
            options={'ordering': ('kon', 'typ', 'glowa', 'kloda', 'noga_przod', 'noga_tyl', 'kopyta', 'step', 'klus', 'ogolny', 'razem')},
        ),
        migrations.AddField(
            model_name='bonitacja',
            name='kloda',
            field=models.IntegerField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
