# Generated by Django 3.2.3 on 2021-07-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0004_auto_20210628_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='kon',
            name='ocena',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
