# Generated by Django 3.2.3 on 2021-07-08 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0005_kon_ocena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kon',
            name='ocena',
        ),
        migrations.CreateModel(
            name='Ocena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='konie.kon')),
            ],
            options={
                'ordering': ('kon',),
            },
        ),
    ]
