# Generated by Django 3.2.3 on 2021-07-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0006_auto_20210708_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocena',
            name='kon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocena_konie', to='konie.kon'),
        ),
    ]
