# Generated by Django 3.2.3 on 2021-07-09 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0009_auto_20210709_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='horse',
        ),
        migrations.AddField(
            model_name='grade',
            name='Kon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='kon', to='konie.kon'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Horse',
        ),
    ]
