# Generated by Django 3.2.3 on 2021-07-09 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0010_auto_20210709_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kon',
            options={},
        ),
    ]
