# Generated by Django 3.2.3 on 2021-07-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('konie', '0011_alter_kon_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='Kon',
        ),
        migrations.AddField(
            model_name='grade',
            name='kon',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='konie.kon'),
            preserve_default=False,
        ),
    ]
